#!/usr/bin/env python3
"""Build the curated npm seed list used by generate_index.py."""

import json
from pathlib import Path


# (npm_package, [tags])
SEEDS = [
    ("express", ["Web框架", "HTTP"]),
    ("koa", ["Web框架", "HTTP"]),
    ("fastify", ["Web框架", "HTTP"]),
    ("hapi", ["Web框架", "HTTP"]),
    ("sails", ["Web框架", "MVC"]),
    ("restify", ["Web框架", "REST"]),
    ("micro", ["Web框架", "异步"]),
    ("polka", ["Web框架", "轻量"]),
    ("next", ["React", "Web框架", "SSR"]),
    ("nuxt", ["Vue", "Web框架", "SSR"]),
    ("gatsby", ["React", "静态站点"]),
    ("astro", ["静态站点", "Web框架"]),
    ("remix", ["Web框架", "React"]),
    ("@remix-run/react", ["Web框架", "React"]),
    ("@sveltejs/kit", ["Web框架", "Svelte"]),
    ("solid-js", ["UI库", "响应式"]),
    ("@solidjs/router", ["路由", "Solid"]),
    ("react", ["UI库", "组件"]),
    ("react-dom", ["UI库", "DOM"]),
    ("react-native", ["移动开发", "UI库"]),
    ("preact", ["UI库", "轻量"]),
    ("vue", ["UI库", "响应式"]),
    ("vue-router", ["路由", "Vue"]),
    ("pinia", ["状态管理", "Vue"]),
    ("svelte", ["UI库", "编译"]),
    ("lit", ["UI库", "Web组件"]),
    ("@angular/core", ["UI库", "Angular"]),
    ("@angular/common", ["Angular", "工具库"]),
    ("angular", ["UI库", "Angular"]),
    ("ember-source", ["UI库", "Ember"]),
    ("backbone", ["MVC", "UI库"]),
    ("jquery", ["DOM", "UI库"]),
    ("htmx.org", ["DOM", "交互"]),
    ("alpinejs", ["DOM", "交互"]),
    ("stimulus", ["DOM", "交互"]),
    ("redux", ["状态管理"]),
    ("@reduxjs/toolkit", ["状态管理", "Redux"]),
    ("react-redux", ["状态管理", "React"]),
    ("zustand", ["状态管理", "React"]),
    ("jotai", ["状态管理", "React"]),
    ("recoil", ["状态管理", "React"]),
    ("mobx", ["状态管理", "响应式"]),
    ("xstate", ["状态机", "状态管理"]),
    ("immer", ["不可变数据", "工具库"]),
    ("reselect", ["状态管理", "选择器"]),
    ("formik", ["表单", "React"]),
    ("react-hook-form", ["表单", "React"]),
    ("yup", ["校验", "表单"]),
    ("zod", ["校验", "模式"]),
    ("joi", ["校验", "模式"]),
    ("validator", ["校验", "工具库"]),
    ("ajv", ["JSON Schema", "校验"]),
    ("class-validator", ["校验", "装饰器"]),
    ("lodash", ["工具库", "函数式"]),
    ("underscore", ["工具库", "函数式"]),
    ("ramda", ["工具库", "函数式"]),
    ("rxjs", ["响应式编程", "流"]),
    ("async", ["异步", "工具库"]),
    ("bluebird", ["Promise", "异步"]),
    ("p-queue", ["队列", "并发"]),
    ("dayjs", ["日期时间", "工具库"]),
    ("moment", ["日期时间", "工具库"]),
    ("moment-timezone", ["日期时间", "时区"]),
    ("date-fns", ["日期时间", "工具库"]),
    ("luxon", ["日期时间", "工具库"]),
    ("chrono-node", ["日期时间", "解析"]),
    ("ms", ["时间", "单位换算"]),
    ("axios", ["HTTP客户端"]),
    ("node-fetch", ["HTTP客户端", "Fetch"]),
    ("undici", ["HTTP客户端", "Fetch"]),
    ("got", ["HTTP客户端"]),
    ("superagent", ["HTTP客户端"]),
    ("request", ["HTTP客户端"]),
    ("isomorphic-fetch", ["HTTP客户端", "Fetch"]),
    ("cross-fetch", ["HTTP客户端", "Fetch"]),
    ("whatwg-fetch", ["HTTP客户端", "Fetch"]),
    ("fetch-mock", ["HTTP", "测试"]),
    ("msw", ["HTTP", "Mock", "测试"]),
    ("cheerio", ["HTML解析", "爬虫"]),
    ("jsdom", ["DOM", "测试"]),
    ("parse5", ["HTML解析"]),
    ("puppeteer", ["浏览器自动化", "测试"]),
    ("playwright", ["浏览器自动化", "测试"]),
    ("selenium-webdriver", ["浏览器自动化", "测试"]),
    ("cypress", ["测试", "浏览器自动化"]),
    ("nightwatch", ["测试", "浏览器自动化"]),
    ("webdriverio", ["测试", "浏览器自动化"]),
    ("jest", ["测试", "断言"]),
    ("vitest", ["测试", "断言"]),
    ("mocha", ["测试", "断言"]),
    ("jasmine", ["测试", "断言"]),
    ("ava", ["测试", "断言"]),
    ("tape", ["测试", "断言"]),
    ("chai", ["测试", "断言"]),
    ("should", ["测试", "断言"]),
    ("expect", ["测试", "断言"]),
    ("sinon", ["测试", "Mock"]),
    ("supertest", ["测试", "HTTP"]),
    ("@testing-library/react", ["测试", "React"]),
    ("@testing-library/jest-dom", ["测试", "DOM断言"]),
    ("@testing-library/vue", ["测试", "Vue"]),
    ("@testing-library/user-event", ["测试", "交互"]),
    ("istanbul", ["测试", "覆盖率"]),
    ("nyc", ["测试", "覆盖率"]),
    ("c8", ["测试", "覆盖率"]),
    ("eslint", ["Lint", "代码质量"]),
    ("@typescript-eslint/parser", ["Lint", "TypeScript"]),
    ("prettier", ["格式化", "代码质量"]),
    ("standard", ["Lint", "代码质量"]),
    ("stylelint", ["Lint", "CSS"]),
    ("husky", ["Git钩子", "代码质量"]),
    ("lint-staged", ["Git钩子", "格式化"]),
    ("typescript", ["语言", "类型系统"]),
    ("ts-node", ["TypeScript", "运行时"]),
    ("tsx", ["TypeScript", "运行时"]),
    ("esbuild", ["构建工具", "打包"]),
    ("webpack", ["构建工具", "打包"]),
    ("webpack-cli", ["构建工具", "命令行"]),
    ("rollup", ["构建工具", "打包"]),
    ("vite", ["构建工具", "开发服务器"]),
    ("parcel", ["构建工具", "打包"]),
    ("snowpack", ["构建工具", "开发服务器"]),
    ("turbo", ["构建工具", "Monorepo"]),
    ("babel-loader", ["构建工具", "Babel"]),
    ("@babel/core", ["编译器", "Babel"]),
    ("@babel/preset-env", ["编译器", "Babel"]),
    ("terser", ["压缩", "构建工具"]),
    ("uglify-js", ["压缩", "构建工具"]),
    ("gulp", ["构建工具", "任务自动化"]),
    ("grunt", ["构建工具", "任务自动化"]),
    ("nvm", ["Node", "版本管理"]),
    ("nodemon", ["开发工具", "热重载"]),
    ("pm2", ["进程管理", "部署"]),
    ("forever", ["进程管理", "部署"]),
    ("concurrently", ["进程管理", "命令行"]),
    ("cross-env", ["环境变量", "跨平台"]),
    ("shelljs", ["Shell", "工具库"]),
    ("execa", ["进程", "Shell"]),
    ("npm-run-all", ["脚本", "任务"]),
    ("dotenv", ["配置", "环境变量"]),
    ("config", ["配置", "环境变量"]),
    ("convict", ["配置", "校验"]),
    ("envalid", ["配置", "环境变量"]),
    ("winston", ["日志", "监控"]),
    ("pino", ["日志", "高性能"]),
    ("bunyan", ["日志"]),
    ("log4js", ["日志"]),
    ("morgan", ["日志", "HTTP"]),
    ("debug", ["日志", "调试"]),
    ("chalk", ["终端", "颜色"]),
    ("colors", ["终端", "颜色"]),
    ("commander", ["命令行", "CLI"]),
    ("yargs", ["命令行", "CLI"]),
    ("minimist", ["命令行", "参数解析"]),
    ("meow", ["命令行", "CLI"]),
    ("prompts", ["命令行", "交互"]),
    ("inquirer", ["命令行", "交互"]),
    ("enquirer", ["命令行", "交互"]),
    ("ora", ["命令行", "进度"]),
    ("boxen", ["终端", "盒子"]),
    ("clui", ["终端", "UI"]),
    ("blessed", ["终端", "TUI"]),
    ("glob", ["文件", "模式匹配"]),
    ("fast-glob", ["文件", "模式匹配"]),
    ("chokidar", ["文件监听"]),
    ("fs-extra", ["文件", "系统"]),
    ("rimraf", ["文件", "删除"]),
    ("mkdirp", ["文件", "目录"]),
    ("graceful-fs", ["文件", "系统"]),
    ("path-to-regexp", ["URL", "路由"]),
    ("qs", ["URL", "查询参数"]),
    ("query-string", ["URL", "查询参数"]),
    ("url-parse", ["URL", "解析"]),
    ("cookie", ["Cookie", "解析"]),
    ("cookie-parser", ["Cookie", "Express"]),
    ("cors", ["CORS", "HTTP"]),
    ("helmet", ["安全", "HTTP头"]),
    ("compression", ["HTTP", "压缩"]),
    ("body-parser", ["HTTP", "请求体"]),
    ("multer", ["文件上传", "HTTP"]),
    ("formidable", ["文件上传", "HTTP"]),
    ("busboy", ["文件上传", "HTTP"]),
    ("sharp", ["图像处理"]),
    ("jimp", ["图像处理"]),
    ("canvas", ["图像", "Canvas"]),
    ("chart.js", ["可视化", "图表"]),
    ("echarts", ["可视化", "图表"]),
    ("d3", ["可视化", "DOM"]),
    ("three", ["3D", "渲染"]),
    ("babylonjs", ["3D", "游戏引擎"]),
    ("pixi.js", ["2D", "渲染", "游戏"]),
    ("phaser", ["游戏引擎", "2D"]),
    ("gsap", ["动画", "交互"]),
    ("animejs", ["动画"]),
    ("framer-motion", ["动画", "React"]),
    ("socket.io", ["WebSocket", "实时"]),
    ("socket.io-client", ["WebSocket", "客户端"]),
    ("ws", ["WebSocket"]),
    ("uWebSockets.js", ["WebSocket", "高性能"]),
    ("engine.io", ["WebSocket", "实时"]),
    ("amqplib", ["AMQP", "消息队列"]),
    ("kafkajs", ["Kafka", "消息队列"]),
    ("ioredis", ["Redis", "NoSQL"]),
    ("redis", ["Redis", "NoSQL"]),
    ("pg", ["数据库驱动", "PostgreSQL"]),
    ("mysql2", ["数据库驱动", "MySQL"]),
    ("sequelize", ["ORM", "数据库"]),
    ("typeorm", ["ORM", "数据库"]),
    ("prisma", ["ORM", "数据库"]),
    ("@prisma/client", ["ORM", "数据库"]),
    ("knex", ["SQL", "查询构建"]),
    ("bookshelf", ["ORM", "数据库"]),
    ("objection", ["ORM", "数据库"]),
    ("mongoose", ["ORM", "MongoDB"]),
    ("mongodb", ["NoSQL", "MongoDB"]),
    ("better-sqlite3", ["数据库", "SQLite"]),
    ("sqlite3", ["数据库", "SQLite"]),
    ("lowdb", ["数据库", "JSON"]),
    ("lokijs", ["数据库", "内存"]),
    ("nedb", ["数据库", "嵌入式"]),
    ("level", ["数据库", "嵌入式"]),
    ("dynamoose", ["NoSQL", "DynamoDB"]),
    ("jsonwebtoken", ["JWT", "安全"]),
    ("jose", ["JWT", "安全"]),
    ("bcryptjs", ["密码哈希", "安全"]),
    ("bcrypt", ["密码哈希", "安全"]),
    ("argon2", ["密码哈希", "安全"]),
    ("crypto-js", ["加密", "安全"]),
    ("node-forge", ["加密", "安全"]),
    ("passport", ["认证", "中间件"]),
    ("passport-jwt", ["认证", "JWT"]),
    ("passport-google-oauth20", ["认证", "OAuth"]),
    ("oauth2orize", ["OAuth", "认证"]),
    ("helmet-csp", ["安全", "CSP"]),
    ("uuid", ["UUID", "工具库"]),
    ("nanoid", ["ID生成", "工具库"]),
    ("shortid", ["ID生成", "工具库"]),
    ("cuid", ["ID生成", "工具库"]),
    ("aws-sdk", ["云服务", "AWS"]),
    ("@aws-sdk/client-s3", ["云服务", "AWS", "存储"]),
    ("@aws-sdk/client-dynamodb", ["云服务", "AWS", "NoSQL"]),
    ("googleapis", ["云服务", "Google"]),
    ("@google-cloud/storage", ["云服务", "存储"]),
    ("@google-cloud/pubsub", ["云服务", "消息队列"]),
    ("@azure/storage-blob", ["云服务", "Azure", "存储"]),
    ("@azure/identity", ["云服务", "Azure", "认证"]),
    ("firebase", ["云服务", "Firebase"]),
    ("@firebase/app", ["云服务", "Firebase"]),
    ("openai", ["AI", "API客户端"]),
    ("@anthropic-ai/sdk", ["AI", "API客户端"]),
    ("langchain", ["AI", "Agent"]),
    ("@langchain/core", ["AI", "LangChain"]),
    ("pdfkit", ["PDF", "生成"]),
    ("pdfjs-dist", ["PDF", "解析"]),
    ("pdf-lib", ["PDF", "生成"]),
    ("jspdf", ["PDF", "生成"]),
    ("exceljs", ["Excel", "Office"]),
    ("xlsx", ["Excel", "Office"]),
    ("docx", ["Word", "Office"]),
    ("html-pdf", ["PDF", "HTML"]),
    ("markdown-it", ["Markdown", "解析"]),
    ("marked", ["Markdown", "解析"]),
    ("remark", ["Markdown", "解析"]),
    ("highlight.js", ["代码高亮"]),
    ("syntaxhighlighter", ["代码高亮"]),
    ("commander", ["CLI", "命令行"]),
]


def main() -> int:
    out = Path(__file__).resolve().parent.parent / "tools" / "seeds"
    out.mkdir(parents=True, exist_ok=True)
    data = [{"name": name, "tags": tags} for name, tags in SEEDS]
    (out / "javascript.json").write_text(
        json.dumps(data, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {len(data)} seeds to {out / 'javascript.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
